# github_integration.py
from github import Github
import time

def push_to_github(repo_name, access_token, file_path, new_content):
    g = Github(access_token)
    repo = g.get_repo(repo_name)
    
    branch_name = f"ai-heal-{int(time.time())}"
    source_branch = repo.get_branch("main")
    
    # Create new branch
    repo.create_git_ref(ref=f"refs/heads/{branch_name}", sha=source_branch.commit.sha)
    
    # Commit fix
    contents = repo.get_contents(file_path, ref="main")
    repo.update_file(
        path=contents.path,
        message="🤖 AI: Healed code crash",
        content=new_content,
        sha=contents.sha,
        branch=branch_name
    )
    
    # Create Pull Request
    pr = repo.create_pull(
        title=f"AI Healing: {file_path}",
        body="This PR was automatically generated by DevOps-Pilot.",
        head=branch_name,
        base="main"
    )
    return pr.html_url